import type { Metadata } from "next";
import "./globals.css";
import { Cairo } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const cairo = Cairo({
  subsets: ["arabic", "latin"],
  display: "auto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cairo.className}`}>
        {children}
      </body>
    </html>
  );
}
